imgBasePath: "myblog" # Base path for images

searchTypes: # List of supported search types
  - regex

directories:
  - dir: "myblog/_posts"
    fileTypes: # Key can be * or ommitted for all files.
      - md


