matrix:

- name: markdown
  sources:
  - 'myblog/_posts/*.md'
  aspell:
    lang: en
  dictionary:
    wordlists:
      - '.github/custom-wordlist.txt'
  pipeline:
  - pyspelling.filters.markdown:
      markdown_extensions:
      - markdown.extensions.extra:
  - pyspelling.filters.html:
      comments: true
      attributes:
      - title
      - alt
      ignores:
      - :matches(code, pre, samp, kbd, var)
      # In HTML:
      # <code>  Defines a piece of computer code
      # <pre>   Defines pre-formatted text
      # <samp>  Defines sample output from a computer program
      # <kbd>   Defines keyboard input
      # <var>   Defines a variable
