apiVersion: v1
kind: Service
metadata:
  name: jekyll-service
  labels:
    app: jekyll
spec:
  selector:
    app: jekyll  
  ports:
    - protocol: TCP
      port: 8085          
      targetPort: 80     
  type: ClusterIP       
