name: Check Image Paths

on:
  pull_request:
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Specify the Python version you want to use

      - name: Install repo dependencies
        run: |
          python -m pip install --upgrade pip
          pip install git+https://github.com/maxherbs/image-validator

      - name: Run validator
        run: |
          image-validator validate -p .github/image-checker.yaml

