name: Check Image Paths
on:
  pull_request:
  push: 
    branches:
      - "*"
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "${{ runner.temp }}/.poetry/bin" >> $GITHUB_PATH

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run Test
        run: |
          poetry run image-validator validate -p .github/image-checker.yaml
